{
 "title": "Jitsi etherpad",
 "tags": [
  "jitsi",
  "etherpad"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "etherpad_server_users_total", "legendFormat": "{{ pod }}" }
   ]
  },
  {
   "title": "Connects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etherpad_server_connects_total[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pending edits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etherpad_server_pending_edits_total",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Disconnects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etherpad_server_disconnects_total[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Failed change",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etherpad_server_failed_change_sets_total",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Edits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "etherpad_server_edits_total", "legendFormat": "{{ pod }}" }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etherpad_server_http_requests_total[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "HTTP requests 500",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etherpad_server_http_500_total[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "etherpad_server_memory_usage", "legendFormat": "{{ pod }}" }
   ]
  }
 ]
}